package jevshadow

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type annotationV2BoundaryFixture struct {
	Contract string `json:"contract"`
	Cases    []struct {
		Name    string          `json:"name"`
		Valid   bool            `json:"valid"`
		Payload json.RawMessage `json:"payload"`
	} `json:"cases"`
}

// These artifacts are generated by jev-alert-shadow/scripts/export_contracts.py.
// The Python schema is authoritative; this vendored copy lets the independently
// built Notification Manager fail CI if its decoder drifts from that boundary.
func TestAnnotationV2DecoderMatchesPythonBoundaryGolden(t *testing.T) {
	fixturePath := filepath.Join("testdata", "annotation-component-v2.boundary-cases.json")
	encoded, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatal(err)
	}
	var fixture annotationV2BoundaryFixture
	if err := json.Unmarshal(encoded, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.Contract != "annotation-component-v2.schema.json" {
		t.Fatalf("unexpected fixture contract: %q", fixture.Contract)
	}
	for _, test := range fixture.Cases {
		t.Run(test.Name, func(t *testing.T) {
			_, err := decodeAnnotation(bytes.NewReader(test.Payload))
			if test.Valid && err != nil {
				t.Fatalf("Python-valid boundary payload was rejected: %v", err)
			}
			if !test.Valid && err == nil {
				t.Fatal("Python-invalid boundary payload was accepted")
			}
		})
	}
}

func TestAnnotationV2DecoderLimitsMatchVendoredPythonSchema(t *testing.T) {
	schemaPath := filepath.Join("testdata", "annotation-component-v2.schema.json")
	encoded, err := os.ReadFile(schemaPath)
	if err != nil {
		t.Fatal(err)
	}
	var schema map[string]interface{}
	if err := json.Unmarshal(encoded, &schema); err != nil {
		t.Fatal(err)
	}
	properties := schema["properties"].(map[string]interface{})

	judgment := stringSchema(properties["judgment_id"].(map[string]interface{}))
	member := properties["member_event_ids"].(map[string]interface{})["items"].(map[string]interface{})
	reason := properties["policy_reason_code"].(map[string]interface{})
	traceURL := stringSchema(properties["trace_url"].(map[string]interface{}))
	actionReference := stringSchema(properties["action_reference"].(map[string]interface{}))

	assertSchemaLimit(t, "judgment_id", judgment, "maxLength", maxV2JudgmentIDCharacters)
	assertSchemaLimit(t, "member_event_ids items", member, "minLength", 1)
	assertSchemaLimit(t, "member_event_ids items", member, "maxLength", maxV2MemberEventIDCharacters)
	assertSchemaLimit(t, "policy_reason_code", reason, "minLength", 1)
	assertSchemaLimit(t, "policy_reason_code", reason, "maxLength", maxV2PolicyReasonCharacters)
	assertSchemaLimit(t, "trace_url", traceURL, "maxLength", maxV2TraceURLCharacters)
	assertSchemaLimit(t, "action_reference", actionReference, "maxLength", maxV2ActionRefCharacters)
	if _, constrained := reason["pattern"]; constrained {
		t.Fatal("policy_reason_code unexpectedly has a character pattern constraint")
	}
}

func stringSchema(property map[string]interface{}) map[string]interface{} {
	if property["type"] == "string" {
		return property
	}
	for _, candidate := range property["anyOf"].([]interface{}) {
		branch := candidate.(map[string]interface{})
		if branch["type"] == "string" {
			return branch
		}
	}
	return nil
}

func assertSchemaLimit(t *testing.T, field string, schema map[string]interface{}, key string, want int) {
	t.Helper()
	if got := int(schema[key].(float64)); got != want {
		t.Fatalf("%s %s = %d, want %d", field, key, got, want)
	}
}
